name: stapl3d
channels:
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python=3
  - pip
  - jupyter
  - ipykernel
  - seaborn
  - numpy<=1.21  # For numba in scanpy
  - pandas
  - pypdf2
  - pyyaml
  - h5py
  - mpi4py
  - scikit-learn
  - pydantic!=1.10.0  # https://pullanswer.com/questions/typeerror-unhashable-type-color-during-qt-resource-compilation
  - napari
  - tifffile
  - czifile
  - nibabel
  - simpleitk
  - stardist
  - scanpy
  - leidenalg
  - pip:
    - git+git://github.com/RiosGroup/scikit-image.git#egg=scikit-image
    - git+git://github.com/RiosGroup/reaflif.git#egg=readlif
    - .
