name: stapl3d
channels:
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python=3
  - pip
  - cython
  - jupyter
  - matplotlib
  - seaborn
  - numpy<=1.21  # For numba in scanpy
  - scipy
  - pandas
  - pypdf2
  - pyyaml
  - h5py
  - mpi4py
  - scikit-image
  - scikit-learn
  - pydantic!=1.10.0  # https://pullanswer.com/questions/typeerror-unhashable-type-color-during-qt-resource-compilation
  - napari
  - tifffile
  - czifile
  - readlif
  - nibabel
  - simpleitk
  - stardist
  - scanpy
  - leidenalg
