name: stapl3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - scikit-image>=0.16.2
  - h5py>=2.10.0
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pyyaml>=5.3.1
  - scipy>=1.4.1
  - pandas>=1.0.4
  - pypdf2>=1.26.0
  - pip>=20.0.2
  - pip:
     - czifile>=2019.7.2
     - nibabel>=3.1.0
