submit_defaults:
    submit:
        array: no
        start: 1
        step: 1
        simul: 0
        wtime: 01:00:00
        mem: 60G
        nodes: 1
        tasks: 1
        conda_env: stapl3d

dirtree:
    datadir:
        stacks: stacks
        blocks: blocks
        channels: channels
        shading: shading
        stitching: stitching
        mask:
        biasfield: biasfield
        profiling: profiling
        jobfiles: jobfiles

dataset:
    name: 200302_RL57_P30T_25x
    alias: P30T_RL
    file_format: czi
    ims_ref_postfix: _ref_uint16
    dapi_channel: 0
    dapi_shift: 0
    blocksize_xy: 1280
    blockmargin_xy: 64
    X: 13984
    Y: 17625
    Z: 109
    C: 8
    T: 1

shading:
    file_format: czi
    params:
        postfix: _shading
        metric: median
        noise_threshold: 1000
        z_range:
        quantile_threshold: 0.8
        polynomial_order: 3
    submit:
        array: channel_plane
        simul: 24
        mem: 10G
        wtime: 01:00:00

shading_postproc:
    params:
    submit:
        array: channel
        wtime: 01:00:00

shading_apply:
    params:
    submit:
        array: stack
        wtime: 01:00:00
        mem: 30G

stitching:
    params:
        postfix: _stitching
        channel: 0

stitching_prep:
    params:
    submit:
        array: no
        wtime: 00:10:00

stitching_load:
    params:
    submit:
        array: channel
        mem: 20G
        wtime: 03:00:00

stitching_calc:
    params:
    submit:
        array: no
        tasks: 24
        mem: 60G
        wtime: 02:00:00

stitching_fuse:
    params:
    submit:
        array: channel
        tasks: 24
        mem: 20G
        wtime: 24:00:00

splitchannels:
    params:
    submit:
        array: channel

mask:
    params:
        postfix: _mask
        sigma: 48.0
        use_median_thresholds: true
        median_factor: 3
        abs_threshold: 1000
        thresholds:
            - 500
            - 1000
            - 2000
            - 3000
            - 4000
            - 5000
            - 10000
        distance_to_edge: true
    submit:
        array: no

ims_aggregate1:
    params:
    submit:
        array: no
        mem: 10G
        wtime: 00:30:00

biasfield:
    params:
        postfix: _biasfield
        mask_in: true
        n_iterations: 50
        n_fitlevels: 4
        n_bspline_cps:
            z: 5
            y: 5
            x: 5
    submit:
        array: channel
        tasks: 24
        mem: 20G
        wtime: 05:00:00

biasfield_stack:
    conda:
        env: stapl3d
    submit:
        array: no
        mem: 20G
        wtime: 01:30:00

biasfield_apply:
    params:
        copy_from_ref: true
        blocksize_xy: 1280
    submit:
        array: channel
        mem: 60G
        wtime: 10:00:00

ims_aggregate2:
    params:
    submit:
        array: no
        mem: 20G
        wtime: 00:10:00

block_segmentation:
    params:
    submit:
        array: block
        mem: 60G
        wtime: 05:00:00

splitblocks:
    params:
        memb_idxs:
            - 3
            - 5
            - 6
            - 7
        memb_weights:
            - 0.5
            - 0.5
            - 1.0
            - 1.0
        nucl_idxs:
            - 0
            - 1
            - 2
            - 4
        nucl_weights:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
        mean_idxs:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
        mean_weights:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
        output_channels:
            - 0
    submit:
        array: block
        mem: 60G
        wtime: 01:00:00

membrane_enhancement:
    params:
        median_filter_par: 0.5
        membrane_filter_par: 1.1
    submit:
        array: block
        mem: 60G
        wtime: 01:00:00

segmentation:
    params:
        ids_memb_mask: memb/planarity
        ids_memb_chan: memb/mean
        ids_nucl_chan: chan/ch00
        ids_dset_mean: mean
        segments_ods: labels_memb_del
        dapi_shift_planes: 0
        nucl_opening_footprint:
            - 3
            - 7
            - 7
        dapi_filter: 'median'
        dapi_sigma: 1
        dapi_dog_sigma1: 2
        dapi_dog_sigma2: 4
        dapi_thr: 5000
        sauvola_window_size:
            - 19
            - 75
            - 75
        sauvola_k: 0.2
        dapi_absmin: 1000
        dapi_erodisk: 3
        dist_max: 5
        peaks_size:
            - 11
            - 19
            - 19
        peaks_thr: 1.16
        peaks_dil_footprint:
            - 3
            - 7
            - 7
        compactness: 0.0
        memb_filter: 'median'
        memb_sigma: 3.0
        planarity_thr: 0.0005
        dset_mask_filter: 'gaussian'
        dset_mask_sigma: 50
        dset_mask_thr: 1000
        steps:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
    submit:
        array: block
        mem: 60G
        wtime: 01:00:00

segmentation_postproc:
    params:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

segmentation_gather:
    params:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

relabel:
    params:
        postfix: _relabeled
    submit:
        array: block
        mem: 10G
        wtime: 00:10:00

relabel_gather:
    params:
        postfix: _relabeled
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

copyblocks:
    params:
        postfix: _fix
    submit:
        array: block
        mem: 10G
        wtime: 00:10:00

copyblocks_gather:
    params:
        postfix: _relabeled_fix
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

zipping:
    params:
        blocksize:
        blockmargin:
        blockrange:
        blocks:
        grp: segm
        ids: labels_memb_del_relabeled_fix
        postfix: _relabeled_fix

zipping_gather:
    params:
        postfix: _relabeled_fix
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

ziplines:
    params:
    submit:
        array: zipline
        mem: 60G
        wtime: 02:00:00

zipquads:
    params:
        axis: 0
    submit:
        array: zipquad
        mem: 60G
        wtime: 01:00:00

zipping_postproc:
    params:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

copydataset:
    params:
        ids: /segm/labels_memb_del_relabeled_fix
        ods: /segm/labels_memb_del_relabeled_fix_full
    submit:
        array: block
        mem: 10G
        wtime: 01:10:00

subsegment:
    params:
        ids: segm/labels_memb_del_relabeled_fix
        ods_full: segm/labels_memb_del_relabeled_fix_full
        ods_memb: segm/labels_memb_del_relabeled_fix_memb
        ods_nucl: segm/labels_memb_del_relabeled_fix_nucl
    submit:
        array: block
        mem: 10G
        wtime: 01:00:00

mergeblocks:
    params:
        ids00:
            ids: segm/labels_memb_del_relabeled_fix_full
            format: h5
            postfix: segm-labels_memb_del_relabeled_fix_full
        ids01:
            ids: segm/labels_memb_del_relabeled_fix_memb
            format: h5
            postfix: segm-labels_memb_del_relabeled_fix_memb
        ids02:
            ids: segm/labels_memb_del_relabeled_fix_nucl
            format: h5
            postfix: segm-labels_memb_del_relabeled_fix_nucl
        ids03:
            ids: nucl/dapi_mask_nuclei
            format: ims
            postfix:
        ids04:
            ids: nucl/dapi_shifted
            format: ims
            postfix:
        ids05:
            ids: memb/mean
            format: ims
            postfix:
    submit:
        array: idss
        mem: 20G
        wtime: 01:00:00

features:
    params:
        ids: segm/labels_memb_del_relabeled_fix
        seg_names:
            - full
            - memb
            - nucl
        min_labelsize: 50
        fset_morph: minimal
        fset_intens: minimal
        memb_idxs:
            - 3
            - 5
            - 6
            - 7
        nucl_idxs:
            - 0
            - 1
            - 2
            - 4
        blocksize_xy: 1280
    submit:
        array: block
        mem: 60G
        wtime: 05:00:00

features_postproc:
    params:
    submit:
        array: no
        mem: 60G
        wtime: 01:00:00
