submit_defaults:
    submit:
        array: no
        start: 1
        step: 1
        simul: 0
        wtime: 01:00:00
        mem: 60G
        nodes: 1
        tasks: 1
        conda_env: stapl3d
        partition: cpu
        gpus_per_node: RTX6000:1

dirtree:
    datadir:
        stacks: stacks
        blocks: blocks
        channels: channels
        shading: shading
        stitching: stitching
        mask:
        biasfield: biasfield
        profiling: profiling
        jobfiles: jobfiles

dataset:
    name: 200302_RL57_P30T_25x
    alias: P30T_RL
    file_format: czi
    ims_ref_postfix: _ref_uint16
    dapi_channel: 0
    dapi_shift: 0
    blocksize_xy: 1280
    blockmargin_xy: 64
    X: 13984
    Y: 17625
    Z: 109
    C: 8
    T: 1

shading:
    file_format: czi
    params:
        postfix: _shading
        metric: median
        noise_threshold: 1000
        z_range:
        quantile_threshold: 0.8
        polynomial_order: 3
    submit:
        array: channel_plane
        simul: 24
        mem: 10G
        wtime: 01:00:00

shading_postproc:
    params:
    submit:
        array: channel
        wtime: 01:00:00

shading_apply:
    params:
    submit:
        array: stack
        wtime: 01:00:00
        mem: 30G

stitching:
    params:
        postfix: _stitching
        channel: 0

stitching_prep:
    params:
    submit:
        array: no
        wtime: 00:10:00

stitching_load:
    params:
    submit:
        array: channel
        mem: 20G
        wtime: 03:00:00

stitching_calc:
    params:
    submit:
        array: no
        tasks: 24
        mem: 60G
        wtime: 02:00:00

stitching_fuse:
    params:
    submit:
        array: channel
        tasks: 24
        mem: 20G
        wtime: 24:00:00

splitchannels:
    params:
    submit:
        array: channel

mask:
    params:
        postfix: _mask
        sigma: 48.0
        use_median_thresholds: true
        median_factor: 3
        abs_threshold: 1000
        thresholds:
            - 500
            - 1000
            - 2000
            - 3000
            - 4000
            - 5000
            - 10000
        distance_to_edge: true
    submit:
        array: no

ims_aggregate1:
    params:
    submit:
        array: no
        mem: 10G
        wtime: 00:30:00

biasfield:
    params:
        postfix: _biasfield
        mask_in: true
        n_iterations: 50
        n_fitlevels: 4
        n_bspline_cps:
            z: 5
            y: 5
            x: 5
    submit:
        array: channel
        tasks: 24
        mem: 20G
        wtime: 05:00:00

biasfield_stack:
    conda:
        env: stapl3d
    submit:
        array: no
        mem: 20G
        wtime: 01:30:00

biasfield_apply:
    params:
        copy_from_ref: true
        blocksize_xy: 1280
    submit:
        array: channel
        mem: 60G
        wtime: 10:00:00

ims_aggregate2:
    params:
    submit:
        array: no
        mem: 20G
        wtime: 00:10:00

block_segmentation:
    params:
    submit:
        array: block
        mem: 60G
        wtime: 05:00:00

splitblocks:
    params:
        memb_idxs:
            - 3
            - 5
            - 6
            - 7
        memb_weights:
            - 0.5
            - 0.5
            - 1.0
            - 1.0
        nucl_idxs:
            - 0
            - 1
            - 2
            - 4
        nucl_weights:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
        mean_idxs:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
        mean_weights:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
            - 1.0
        output_channels:
            - 0
    submit:
        array: block
        mem: 60G
        wtime: 01:00:00

membrane_enhancement:
    params:
        median_filter_par: 0.5
        membrane_filter_par: 1.1
    submit:
        array: block
        mem: 60G
        wtime: 01:00:00

segmentation:

    params:

        prep_dset:
            ids_image: mean
            ods_image: prep
            filter:
                inplane: true
                type: 'gaussian'
                sigma: 50.0

        mask_dset:
            ids_image: prep
            ods_mask: mask
            threshold: 1000.0

        prep_nucl:
            ids_image: chan/ch00
            ods_image: nucl/prep
            shift_planes:
                n_planes: 0
                postfix: _shifted
            opening:
                selem: null
                postfix: _opened
            filter:
                inplane: true
                type: 'median'
                sigma: 1.0

        prep_unet:
            ids_image: nucl/unet_stapl3d
            ods_image: nucl/unet_stapl3d_prep
            shift_planes:
                n_planes: 3

        mask_nucl:
            ids_image: nucl/unet_stapl3d_prep
            ods_mask: nucl/mask
            threshold: 0.9
            fill: true

        prep_memb:
            ids_image: memb/mean
            ods_image: memb/prep
            filter:
                inplane: true
                type: 'median'
                sigma: 1.0

        mask_memb:
            ids_image: memb/unet_stapl3d
            ods_mask: memb/mask
            threshold: 0.6

        combine_masks:
            ids_nucl: nucl/mask
            ids_memb: memb/mask
            ods_mask: segm/seeds_mask
            opening_footprint:
            - 3
            - 7
            - 7

        seed:
            ids_mask: segm/seeds_mask
            ids_image: nucl/prep
            ods_labels: segm/labels_edt
            edt:
                threshold: 5.0
                postfix: _edt
            filter:
                inplane: false
                type: 'dog'
                sigma1: 2.0
                sigma2: 4.0
                min: 1.00
                max: 1.01
                postfix: _dog
            peaks:
                threshold: 1.16
                window:
                - 11
                - 19
                - 19
                dilate:
                    footprint:
                    - 3
                    - 7
                    - 7
                    postfix: _dil
            seeds:
                threshold: 1.16

        segment:
            ids_image: memb/prep
            ids_labels: segm/labels_edt
            ods_labels: segm/labels
            watershed:
                compactness: 0.80
                voxel_spacing:
                    - 4
                    - 1
                    - 1
                postfix: _ws0
            filter:
                ids_mask: prep
                postfix: _dset

    submit:
        array: block
        mem: 60G
        wtime: 01:00:00

segmentation_postproc:
    params:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

segmentation_gather:
    params:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

relabel:
    params:
        postfix: _relabeled
    submit:
        array: block
        mem: 10G
        wtime: 00:10:00

relabel_gather:
    params:
        postfix: _relabeled
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

copyblocks:
    params:
        postfix: _fix
    submit:
        array: block
        mem: 10G
        wtime: 00:10:00

copyblocks_gather:
    params:
        postfix: _relabeled_fix
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

zipping:
    params:
        blocksize:
        blockmargin:
        blockrange:
        blocks:
        grp: segm
        ids: labels_memb_del_relabeled_fix
        postfix: _relabeled_fix

zipping_gather:
    params:
        postfix: _relabeled_fix
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

ziplines:
    params:
    submit:
        array: zipline
        mem: 60G
        wtime: 02:00:00

zipquads:
    params:
        axis: 0
    submit:
        array: zipquad
        mem: 60G
        wtime: 01:00:00

zipping_postproc:
    params:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00

copydataset:
    params:
        ids: /segm/labels_memb_del_relabeled_fix
        ods: /segm/labels_memb_del_relabeled_fix_full
    submit:
        array: block
        mem: 10G
        wtime: 01:10:00

subsegment:
    params:
        ids: segm/labels_memb_del_relabeled_fix
        ods_full: segm/labels_memb_del_relabeled_fix_full
        ods_memb: segm/labels_memb_del_relabeled_fix_memb
        ods_nucl: segm/labels_memb_del_relabeled_fix_nucl
    submit:
        array: block
        mem: 10G
        wtime: 01:00:00

mergeblocks:
    params:
        ids00:
            ids: segm/labels_memb_del_relabeled_fix_full
            format: h5
            postfix: segm-labels_memb_del_relabeled_fix_full
            is_labelimage: true
        ids01:
            ids: segm/labels_memb_del_relabeled_fix_memb
            format: h5
            postfix: segm-labels_memb_del_relabeled_fix_memb
            is_labelimage: true
        ids02:
            ids: segm/labels_memb_del_relabeled_fix_nucl
            format: h5
            postfix: segm-labels_memb_del_relabeled_fix_nucl
            is_labelimage: true
        ids03:
            ids: nucl/dapi_mask_nuclei
            format: ims
            postfix:
        ids04:
            ids: nucl/dapi_shifted
            format: ims
            postfix:
        ids05:
            ids: memb/mean
            format: ims
            postfix:
        ids06:
            ids: memb/3dunet
            format: h5
            postfix:
            elsize:
                - 1.2048
                - 0.3321
                - 0.3321
            inlayout: czyx
            squeeze: c
        ids07:
            ids: probs
            format: h5
            postfix:
    submit:
        array: idss
        mem: 60G
        wtime: 05:00:00

features:
    params:
        ids: segm/labels_memb_del_relabeled_fix
        seg_names:
            - full
            - memb
            - nucl
        min_labelsize: 50
        fset_morph: minimal
        fset_intens: minimal
        memb_idxs:
            - 3
            - 5
            - 6
            - 7
        nucl_idxs:
            - 0
            - 1
            - 2
            - 4
        blocksize_xy: 1280
    submit:
        array: block
        mem: 60G
        wtime: 05:00:00

features_postproc:
    params:
    submit:
        array: no
        mem: 60G
        wtime: 01:00:00

stardist_train:
    params:
        stardir: /hpc/pmc_rios/mkleinnijenhuis/stardist_kidney
        model_name: stardist
    submit:
        array: no
        mem: 10G
        wtime: 96:00:00
        partition: gpu
        gpus_per_node: RTX6000:1
        conda_env: tf-gpu

stardist_nblocks:
    params:
    submit:
        array: no
        mem: 10G
        wtime: 00:10:00
        conda_env: tf

stardist_predict:
    params:
        stardir: /hpc/pmc_rios/mkleinnijenhuis/stardist_kidney
        model_name: stardist
        dapi_postfix: _nucl-dapi_shifted
        nomi: 0
        noma: 24645
    submit:
        array: stardistblock
        mem: 110G
        wtime: 04:00:00
        tasks: 24
        conda_env: tf

stardist_gather:
    params:
        postfix:
    submit:
        array: no
        mem: 1G
        wtime: 00:10:00
        conda_env: tf

stardist_mergeblocks:
    params:
    submit:
        array: no
        mem: 100G
        wtime: 24:00:00
        conda_env: tf

unet3d_memb_train:
    params:
        unetdir: /hpc/pmc_rios/mkleinnijenhuis/unet3d_memb_kidney
        modelname: multiresGT_memb
        ids_image: raw_memb
        ids_label: label_cell
    submit:
        conda_env: 3dunet
        partition: gpu
        tasks: 8
        gpus_per_node: RTX6000:4
        wtime: 96:00:00

unet3d_memb_predict:
    params:
        unetdir: /hpc/pmc_rios/mkleinnijenhuis/unet3d_memb_kidney
        modelname: multiresGT_memb
        ids_image: memb/mean
        ps_blockdir: blocks_ps
    submit:
        array: block
        conda_env: 3dunet
        partition: gpu
        tasks: 8
        gpus_per_node: RTX6000:4
        wtime: 96:00:00

unet3d_nucl_train:
    params:
        unetdir: /hpc/pmc_rios/mkleinnijenhuis/unet3d_nucl_kidney
        modelname: multiresGT_nucl
        ids_image: raw_nucl
        ids_label: label_nucl
    submit:
        conda_env: 3dunet
        partition: gpu
        tasks: 8
        gpus_per_node: RTX6000:1
        wtime: 96:00:00

unet3d_nucl_predict:
    params:
        unetdir: /hpc/pmc_rios/mkleinnijenhuis/unet3d_nucl_kidney
        modelname: multiresGT_nucl
        ids_image: nucl/mean
        ps_blockdir: blocks_ps
    submit:
        array: block
        conda_env: 3dunet
        partition: gpu
        tasks: 8
        gpus_per_node: RTX6000:1
        wtime: 02:00:00

plantseg_predict:
    params:
        unetdir: /hpc/pmc_rios/mkleinnijenhuis/plant-seg_kidney
        modelname: kidney_confocal_3d_unet
        ps_blockdir: blocks_ps
    submit:
        array: block
        tasks: 1
        conda_env: plant-seg
        partition: gpu
        gpus_per_node: RTX6000:1
        mem: 20G
        wtime: 02:00:00

splitblocks_ki67:
    params:
    submit:
        array: block
        mem: 20G
        wtime: 00:20:00

apply_ilastik:
    params:
        pixprob_trainingset: 190910_rl57_fungi_16bit_25x_125um_corr-stitching_02496-03904_12736-14144_00000-00106_ki67_fullBG_11feats
        opf: _ki67_iactBG_11feats_Probabilities
        ods: probs
    submit:
        array: block
        tasks: 12
        mem: 60G
        wtime: 05:00:00

mergeblocks_ilastik:
    params:
        ipf: _ki67_iactBG_11feats_Probabilities
        ids00:
            ids: probs
            format: h5
            postfix:
    submit:
        array: idss
        mem: 20G
        wtime: 01:00:00
