def get_trainsets():
    trainsets = {
        'ID01': {
            'filestem_train': 'stardist_train',
            'ids_dapi': 'data',
            'ids_memb': '',
            'ids_label': 'nucl',
            'h5_path_pat': '{}.h5/{:03d}',
            'axis_norm': (0, 1, 2),
            'z_range': [20, 84],
            'trainblock_list': list(range(0, 18)),
            'ind_val': [],
        },
        'ID02': {
            'filestem_train': 'stardist_trainset2',
            'ids_dapi': 'raw_dapi',
            'ids_memb': 'raw_memb',
            'ids_label': 'man_nucl',
            'h5_path_pat': '{}.h5/{:03d}',
            'axis_norm': (0, 1, 2),
            'z_range': [20, 84],
            'trainblock_list': list(range(0, 18)),
            'ind_val': [],
        },
        'ID03': {
            'filestem_train': 'stardist_trainset2',
            'ids_dapi': 'raw_dapi',
            'ids_memb': 'raw_memb',
            'ids_label': 'man_nucl',
            'h5_path_pat': '{}.h5/{:03d}',
            'axis_norm': (0, 1, 2),
            'z_range': [8, 106],
            'trainblock_list': [1, 2, 3, 4, 5, 6, 7, 8, 10],
            'ind_val': [1, 5],
        },
        'ID04': {
            'filestem_train': 'stardist_trainset2_curated_step00',
            'ids_dapi': 'raw_dapi',
            'ids_memb': 'raw_memb',
            'ids_label': 'man_nucl',
            'h5_path_pat': '{}.h5/step00_patch{:02d}',
            'axis_norm': (0, 1, 2),
            'z_range': [0, 25],
            'trainblock_list': [0, 1, 2, 3, 4, 5, 6, 7],
            'ind_val': [1, 5],
        },
        'ID05': {
            'filestem_train': 'stardist_trainset2_fromscratch',
            'ids_dapi': 'raw_dapi',
            'ids_memb': 'raw_memb',
            'ids_label': 'man_nucl',
            'h5_path_pat': '{}.h5/block004_patch{:02d}',
            'axis_norm': (0, 1, 2),
            'z_range': [0, 25],
            'trainblock_list': [0, 1, 2, 3],
            'ind_val': [1],
        },
        'ID06': {
            'filestem_train': 'stardist_trainset2',
            'ids_dapi': 'raw_dapi',
            'ids_memb': 'raw_memb',
            'ids_label': 'lbl_nucl',
            'h5_path_pat': '{}.h5/{:03d}',
            'axis_norm': (0, 1, 2),
            'z_range': [8, 106],
            'trainblock_list': list(range(0, 20)) + list(range(34, 54)),
            'ind_val': [],
        },
    }

    return trainsets


def get_runs():
    runs = {
        'testrun_1': {
            'trainsets': ['ID01'],
            'train_patch_size': (40, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (), 'int_fac': [], 'int_add': [], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_2ch': {
            'trainsets': ['ID02'],
            'train_patch_size': (40, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': True,
            'augmenter': {'rotflip_axis': (), 'int_fac': [], 'int_add': [], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_man': {
            'trainsets': ['ID03'],
            'train_patch_size': (64, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (), 'int_fac': [], 'int_add': [], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_man_aug': {
            'trainsets': ['ID03'],
            'train_patch_size': (64, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.6, 2.0], 'int_add': [-0.2, 0.2], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_man_aug2': {
            'trainsets': ['ID03'],
            'train_patch_size': (64, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_man_curated': {
            'trainsets': ['ID04'],
            'train_patch_size': (25, 128, 128),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_man_fromscratch': {
            'trainsets': ['ID05'],
            'train_patch_size': (25, 128, 128),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_combined': {
            'trainsets': ['ID04', 'ID05'],
            'train_patch_size': (25, 128, 128),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_combined_2ch': {
            'trainsets': ['ID04', 'ID05'],
            'train_patch_size': (25, 128, 128),
            'grid': (),
            'n_rays': 96,
            'use_memb': True,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'testrun_combined_grid111': {
            'trainsets': ['ID04', 'ID05'],
            'train_patch_size': (25, 128, 128),
            'grid': (1, 1, 1),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [],
        },
        'stapl3d_to_stardist': {
            'trainsets': ['ID06'],
            'train_patch_size': (64, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [0, 24645],
        },
        'testmodel': {
            'trainsets': ['ID06'],
            'train_patch_size': (64, 96, 96),
            'grid': (),
            'n_rays': 96,
            'use_memb': False,
            'augmenter': {'rotflip_axis': (1, 2), 'int_fac': [0.8, 1.2], 'int_add': [-0.1, 0.1], 'scale_axis': (), 'scale_fac': []},
            'normalizer': [0, 24645],
        },
    }

    return runs
