manual_seed: 0
model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: [32, 64, 128, 256]
  num_groups: 8
  final_sigmoid: true
  is_segmentation: true
trainer:
  checkpoint_dir: "UNETDIR/models/MODELNAME"
  resume: null
  validate_after_iters: 1000
  log_after_iters: 100
  epochs: 200
  iters: 60000
  eval_score_higher_is_better: True
loss:
  name: BCEWithLogitsLoss
  skip_last_target: true
optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00001
eval_metric:
  name: BlobsAveragePrecision
  thresholds: [0.4, 0.5, 0.6, 0.7, 0.8]
  metric: 'ap'
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.2
  patience: 8
loaders:
  dataset: StandardHDF5Dataset
  batch_size: 1
  num_workers: 8
  raw_internal_path: raw
  label_internal_path: label
  weight_internal_path: null
  train:
    file_paths:
      - "UNETDIR/data/train"
    slice_builder:
      name: FilterSliceBuilder
      patch_shape:
      - 48
      - 80
      - 80
      stride_shape:
      - 20
      - 40
      - 40
      threshold: 0.01
      slack_acceptance: 0.01
    transformer:
      raw:
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
        - name: BlobsToMask
          append_label: true
          boundary: false
        - name: ToTensor
          expand_dims: false
  val:
    file_paths:
    - "UNETDIR/data/val"
    slice_builder:
      name: FilterSliceBuilder
      patch_shape:
      - 48
      - 80
      - 80
      stride_shape:
      - 20
      - 40
      - 40
      threshold: 0.01
      slack_acceptance: 0.01
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: BlobsToMask
          append_label: true
          boundary: false
        - name: ToTensor
          expand_dims: false
