model_path: "UNETDIR/models/MODELNAME/best_checkpoint.pytorch"
model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: [32, 64, 128, 256]
  num_groups: 8
  final_sigmoid: true
  is_segmentation: true
predictor:
  name: 'StandardPredictor'
loaders:
  batch_size: 1
  mirror_padding: [16, 32, 32]
  raw_internal_path: IDS_IMAGE
  num_workers: 8
  output_dir: "PATH_TO_THE_TEST_SET/predictions_nucl_MODELNAME"
  test:
    file_paths:
      - "PATH_TO_THE_TEST_SET"
    slice_builder:
      name: SliceBuilder
      patch_shape: [80, 170, 170]
      stride_shape: [40, 80, 80]
    transformer:
        raw:
          - name: Standardize
          - name: ToTensor
            expand_dims: true
